//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace Quan_ly_phong_tro
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<Amount>();
                db.CreateTable<Customer>();
                db.CreateTable<Money_Type>();
                db.CreateTable<Room>();
            }
        }
    }
    public partial class Amount
    {
        [PrimaryKey]
        [Unique(Name = "Amount_id_uindex", Order = 0)]
        [MaxLength(50)]
        public String id { get; set; }
        
        [MaxLength(50)]
        public String roomId { get; set; }
        
        public Int32 dien { get; set; }
        public Int32 nuoc { get; set; }
        
        public Int32 phong { get; set; }
        
        public DateTime date_create { get; set; }
        
        [MaxLength(50)]
        public String name_room { get; set; }
        
    }
    
    public partial class Customer
    {
        [MaxLength(50)]
        public String name { get; set; }
        
        [MaxLength(50)]
        public String cmnd { get; set; }
        
        public Int32 birthYear { get; set; }
        
        [MaxLength(50)]
        public String address { get; set; }
        
        public Int32 room { get; set; }
        
        [MaxLength(50)]
        public String numberPhone1 { get; set; }
        
        [MaxLength(50)]
        public String numberPhone2 { get; set; }
        
        public DateTime dateRent { get; set; }
        
        [MaxLength(50)]
        public String gender { get; set; }
        
        [MaxLength(50)]
        public String jobCustomer { get; set; }
        
        [MaxLength(50)]
        public String avatar { get; set; }
        
        public DateTime date_create { get; set; }
        
    }
    
    public partial class Money_Type
    {
        [PrimaryKey]
        public Int32 id { get; set; }
        
        [MaxLength(50)]
        public String type { get; set; }
        
        public Int32 price { get; set; }
        
        public DateTime date_create { get; set; }
        
    }
    
    public partial class Room
    {
        [MaxLength(50)]
        public String nameRoom { get; set; }
        
        [PrimaryKey, AutoIncrement]
        public Int32 idRoom { get; set; }
        
        public Int32 statusRoom { get; set; }
        
    }
    
}
